<script setup lang="ts">
import { computed } from 'vue'
import {
  HomeIcon,
  FolderIcon,
  FolderOpenIcon,
  DocumentIcon,
  PhotoIcon,
  FilmIcon,
  MusicalNoteIcon,
  DocumentTextIcon,
  ArchiveBoxIcon,
  TagIcon,
  Cog6ToothIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  CheckIcon,
  XMarkIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowPathIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  EyeIcon,
  EyeSlashIcon,
  StarIcon,
  HeartIcon,
  TrashIcon,
  PencilIcon,
  PencilSquareIcon,
  ClockIcon,
  CalendarIcon,
  CloudIcon,
  CloudArrowUpIcon,
  CloudArrowDownIcon,
  ServerIcon,
  ComputerDesktopIcon,
  RectangleStackIcon,
  Squares2X2Icon,
  ListBulletIcon,
  TableCellsIcon,
  AdjustmentsHorizontalIcon,
  FunnelIcon,
  InformationCircleIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  QuestionMarkCircleIcon,
  BoltIcon,
  SparklesIcon,
  GlobeAltIcon,
  LinkIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentCheckIcon,
  UserIcon,
  UsersIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  BellIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  Bars3Icon,
  Bars4Icon,
  WindowIcon,
  MinusIcon,
  Square2StackIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ForwardIcon,
  BackwardIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  MicrophoneIcon,
  CameraIcon,
  VideoCameraIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  CommandLineIcon,
  BugAntIcon,
  LightBulbIcon,
  MoonIcon,
  SunIcon,
  FireIcon,
  TrophyIcon,
  RocketLaunchIcon,
  ClipboardIcon,
  CubeIcon,
  CubeTransparentIcon,
  BeakerIcon,
  AcademicCapIcon,
  BookOpenIcon,
  NewspaperIcon,
  PresentationChartBarIcon,
  ChartBarIcon,
  ChartPieIcon,
  CircleStackIcon,
} from '@heroicons/vue/24/outline'

import {
  StarIcon as StarIconSolid,
  HeartIcon as HeartIconSolid,
  CheckIcon as CheckIconSolid,
  XMarkIcon as XMarkIconSolid,
  PlusIcon as PlusIconSolid,
  HomeIcon as HomeIconSolid,
  FolderIcon as FolderIconSolid,
  Cog6ToothIcon as Cog6ToothIconSolid,
  UserIcon as UserIconSolid,
} from '@heroicons/vue/24/solid'

const props = withDefaults(defineProps<{
  name: string
  solid?: boolean
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  class?: string | Record<string, boolean>
}>(), {
  solid: false,
  size: 'md',
})

const sizeMap = {
  xs: 'w-3 h-3',
  sm: 'w-4 h-4',
  md: 'w-5 h-5',
  lg: 'w-6 h-6',
  xl: 'w-8 h-8',
}

const iconMap: Record<string, any> = {
  home: { outline: HomeIcon, solid: HomeIconSolid },
  folder: { outline: FolderIcon, solid: FolderIconSolid },
  'folder-open': { outline: FolderOpenIcon, solid: FolderOpenIcon },
  'folder-plus': { outline: FolderIcon, solid: FolderIconSolid },
  file: { outline: DocumentIcon, solid: DocumentIcon },
  image: { outline: PhotoIcon, solid: PhotoIcon },
  video: { outline: FilmIcon, solid: FilmIcon },
  audio: { outline: MusicalNoteIcon, solid: MusicalNoteIcon },
  document: { outline: DocumentTextIcon, solid: DocumentTextIcon },
  archive: { outline: ArchiveBoxIcon, solid: ArchiveBoxIcon },
  tag: { outline: TagIcon, solid: TagIcon },
  settings: { outline: Cog6ToothIcon, solid: Cog6ToothIconSolid },
  search: { outline: MagnifyingGlassIcon, solid: MagnifyingGlassIcon },
  plus: { outline: PlusIcon, solid: PlusIconSolid },
  check: { outline: CheckIcon, solid: CheckIconSolid },
  close: { outline: XMarkIcon, solid: XMarkIconSolid },
  'chevron-right': { outline: ChevronRightIcon, solid: ChevronRightIcon },
  'chevron-left': { outline: ChevronLeftIcon, solid: ChevronLeftIcon },
  'chevron-down': { outline: ChevronDownIcon, solid: ChevronDownIcon },
  'chevron-up': { outline: ChevronUpIcon, solid: ChevronUpIcon },
  'arrow-left': { outline: ArrowLeftIcon, solid: ArrowLeftIcon },
  'arrow-right': { outline: ArrowRightIcon, solid: ArrowRightIcon },
  'arrow-up': { outline: ArrowUpIcon, solid: ArrowUpIcon },
  'arrow-down': { outline: ArrowDownIcon, solid: ArrowDownIcon },
  refresh: { outline: ArrowPathIcon, solid: ArrowPathIcon },
  download: { outline: ArrowDownTrayIcon, solid: ArrowDownTrayIcon },
  upload: { outline: ArrowUpTrayIcon, solid: ArrowUpTrayIcon },
  eye: { outline: EyeIcon, solid: EyeIcon },
  'eye-off': { outline: EyeSlashIcon, solid: EyeSlashIcon },
  star: { outline: StarIcon, solid: StarIconSolid },
  heart: { outline: HeartIcon, solid: HeartIconSolid },
  trash: { outline: TrashIcon, solid: TrashIcon },
  edit: { outline: PencilIcon, solid: PencilIcon },
  'edit-box': { outline: PencilSquareIcon, solid: PencilSquareIcon },
  clock: { outline: ClockIcon, solid: ClockIcon },
  calendar: { outline: CalendarIcon, solid: CalendarIcon },
  cloud: { outline: CloudIcon, solid: CloudIcon },
  'cloud-upload': { outline: CloudArrowUpIcon, solid: CloudArrowUpIcon },
  'cloud-download': { outline: CloudArrowDownIcon, solid: CloudArrowDownIcon },
  server: { outline: ServerIcon, solid: ServerIcon },
  desktop: { outline: ComputerDesktopIcon, solid: ComputerDesktopIcon },
  stack: { outline: RectangleStackIcon, solid: RectangleStackIcon },
  grid: { outline: Squares2X2Icon, solid: Squares2X2Icon },
  list: { outline: ListBulletIcon, solid: ListBulletIcon },
  table: { outline: TableCellsIcon, solid: TableCellsIcon },
  filter: { outline: FunnelIcon, solid: FunnelIcon },
  adjust: { outline: AdjustmentsHorizontalIcon, solid: AdjustmentsHorizontalIcon },
  info: { outline: InformationCircleIcon, solid: InformationCircleIcon },
  'error-circle': { outline: ExclamationCircleIcon, solid: ExclamationCircleIcon },
  warning: { outline: ExclamationTriangleIcon, solid: ExclamationTriangleIcon },
  question: { outline: QuestionMarkCircleIcon, solid: QuestionMarkCircleIcon },
  bolt: { outline: BoltIcon, solid: BoltIcon },
  sparkles: { outline: SparklesIcon, solid: SparklesIcon },
  globe: { outline: GlobeAltIcon, solid: GlobeAltIcon },
  link: { outline: LinkIcon, solid: LinkIcon },
  copy: { outline: ClipboardDocumentIcon, solid: ClipboardDocumentIcon },
  'copy-check': { outline: ClipboardDocumentCheckIcon, solid: ClipboardDocumentCheckIcon },
  user: { outline: UserIcon, solid: UserIconSolid },
  users: { outline: UsersIcon, solid: UsersIcon },
  lock: { outline: LockClosedIcon, solid: LockClosedIcon },
  unlock: { outline: LockOpenIcon, solid: LockOpenIcon },
  key: { outline: KeyIcon, solid: KeyIcon },
  bell: { outline: BellIcon, solid: BellIcon },
  chat: { outline: ChatBubbleLeftRightIcon, solid: ChatBubbleLeftRightIcon },
  'chat-dots': { outline: ChatBubbleOvalLeftEllipsisIcon, solid: ChatBubbleOvalLeftEllipsisIcon },
  menu: { outline: Bars3Icon, solid: Bars3Icon },
  'menu-alt': { outline: Bars4Icon, solid: Bars4Icon },
  window: { outline: WindowIcon, solid: WindowIcon },
  minus: { outline: MinusIcon, solid: MinusIcon },
  square: { outline: Square2StackIcon, solid: Square2StackIcon },
  play: { outline: PlayIcon, solid: PlayIcon },
  pause: { outline: PauseIcon, solid: PauseIcon },
  stop: { outline: StopIcon, solid: StopIcon },
  forward: { outline: ForwardIcon, solid: ForwardIcon },
  backward: { outline: BackwardIcon, solid: BackwardIcon },
  'volume-high': { outline: SpeakerWaveIcon, solid: SpeakerWaveIcon },
  'volume-off': { outline: SpeakerXMarkIcon, solid: SpeakerXMarkIcon },
  mic: { outline: MicrophoneIcon, solid: MicrophoneIcon },
  camera: { outline: CameraIcon, solid: CameraIcon },
  'video-camera': { outline: VideoCameraIcon, solid: VideoCameraIcon },
  code: { outline: CodeBracketIcon, solid: CodeBracketIcon },
  'code-box': { outline: CodeBracketSquareIcon, solid: CodeBracketSquareIcon },
  terminal: { outline: CommandLineIcon, solid: CommandLineIcon },
  bug: { outline: BugAntIcon, solid: BugAntIcon },
  bulb: { outline: LightBulbIcon, solid: LightBulbIcon },
  moon: { outline: MoonIcon, solid: MoonIcon },
  sun: { outline: SunIcon, solid: SunIcon },
  fire: { outline: FireIcon, solid: FireIcon },
  trophy: { outline: TrophyIcon, solid: TrophyIcon },
  rocket: { outline: RocketLaunchIcon, solid: RocketLaunchIcon },
  clipboard: { outline: ClipboardIcon, solid: ClipboardIcon },
  cube: { outline: CubeIcon, solid: CubeIcon },
  'cube-transparent': { outline: CubeTransparentIcon, solid: CubeTransparentIcon },
  beaker: { outline: BeakerIcon, solid: BeakerIcon },
  academic: { outline: AcademicCapIcon, solid: AcademicCapIcon },
  book: { outline: BookOpenIcon, solid: BookOpenIcon },
  newspaper: { outline: NewspaperIcon, solid: NewspaperIcon },
  chart: { outline: PresentationChartBarIcon, solid: PresentationChartBarIcon },
  'chart-bar': { outline: ChartBarIcon, solid: ChartBarIcon },
  'chart-pie': { outline: ChartPieIcon, solid: ChartPieIcon },
  database: { outline: CircleStackIcon, solid: CircleStackIcon },
}

const iconComponent = computed(() => {
  const icon = iconMap[props.name]
  if (!icon) {
    console.warn(`Icon "${props.name}" not found`)
    return QuestionMarkCircleIcon
  }
  return props.solid ? icon.solid : icon.outline
})

const sizeClass = computed(() => sizeMap[props.size])
</script>

<template>
  <component
    :is="iconComponent"
    :class="[sizeClass, props.class]"
    aria-hidden="true"
  />
</template>
